[package]
name = "zonys-core"
version = "0.0.0"
edition = "2021"

[dependencies]
bindcode = "2.0.0-rc.1"
jail = { path = "../jail" }
liquid = { version = "0.26" }
nix = { version = "0.24", features = ["fs"] }
serde = { version = "1", features = ["derive"] }
serde_yaml = "0.8"
tokio = { version = "1", features = ["full"] }
uuid = { version = "0.8", features = ["v4", "serde"] }
zfs = { path = "../zfs" }
