[package]
name = "zonys-cli"
version = "0.10.0"
edition = "2021"

[dependencies]
clap = { version = "3", features = ["color", "derive", "suggestions"] }
serde_yaml = "0.8"
zonys-core = { path = "../zonys-core" }
