---
version: experimental

type: jail

variables:
  freebsd:
    version:
      architecture: amd64
      major: 13
      minor: 2
      channel: RELEASE
    url:
      scheme: https
      authority: ftp.freebsd.org
      path: "/pub/FreeBSD/releases/{{ freebsd.version.architecture }}/{{ freebsd.version.major }}.{{ freebsd.version.minor }}-{{ freebsd.version.channel }}/{{ freebsd.url.archive }}"
      archive: "base.txz"
      full: "{{ freebsd.url.scheme }}://{{ freebsd.url.authority }}{{ freebsd.url.path }}"

from: "{{ freebsd.url.full }}"
