---
version: 1

type: jail

variables:
  foo_key: foo
  bar_value: bar

execute:
  start:
    on:
      - target: parent
        program: /usr/bin/env

      - target: parent
        program: /usr/bin/env
        environment_variables:
          foo: bar

      - target: parent
        program: /usr/bin/env
        environment_variables:
          "{{ foo_key }}": "{{ bar_value }}"

network: parent
